// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'domain.freezed.dart';

class AssetLocationView {
  final String assetId;
  final String locationId;
  final String rootId;
  final String absolutePath;
  final String displayPath;
  final String relativePath;
  final String previewPath;
  final BigInt fileSize;
  final PlatformInt64? createdUnixMs;
  final PlatformInt64 modifiedUnixMs;
  final FileIdentityEvidence? fileIdentity;
  final int width;
  final int height;
  final PreviewStatus previewStatus;
  final String? previewIssueCode;
  final String? previewIssueMessage;
  final String metadataEngineId;
  final String metadataEngineVersion;
  final CaptureTimeEvidence? captureTime;

  const AssetLocationView({
    required this.assetId,
    required this.locationId,
    required this.rootId,
    required this.absolutePath,
    required this.displayPath,
    required this.relativePath,
    required this.previewPath,
    required this.fileSize,
    this.createdUnixMs,
    required this.modifiedUnixMs,
    this.fileIdentity,
    required this.width,
    required this.height,
    required this.previewStatus,
    this.previewIssueCode,
    this.previewIssueMessage,
    required this.metadataEngineId,
    required this.metadataEngineVersion,
    this.captureTime,
  });

  @override
  int get hashCode =>
      assetId.hashCode ^
      locationId.hashCode ^
      rootId.hashCode ^
      absolutePath.hashCode ^
      displayPath.hashCode ^
      relativePath.hashCode ^
      previewPath.hashCode ^
      fileSize.hashCode ^
      createdUnixMs.hashCode ^
      modifiedUnixMs.hashCode ^
      fileIdentity.hashCode ^
      width.hashCode ^
      height.hashCode ^
      previewStatus.hashCode ^
      previewIssueCode.hashCode ^
      previewIssueMessage.hashCode ^
      metadataEngineId.hashCode ^
      metadataEngineVersion.hashCode ^
      captureTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetLocationView &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          locationId == other.locationId &&
          rootId == other.rootId &&
          absolutePath == other.absolutePath &&
          displayPath == other.displayPath &&
          relativePath == other.relativePath &&
          previewPath == other.previewPath &&
          fileSize == other.fileSize &&
          createdUnixMs == other.createdUnixMs &&
          modifiedUnixMs == other.modifiedUnixMs &&
          fileIdentity == other.fileIdentity &&
          width == other.width &&
          height == other.height &&
          previewStatus == other.previewStatus &&
          previewIssueCode == other.previewIssueCode &&
          previewIssueMessage == other.previewIssueMessage &&
          metadataEngineId == other.metadataEngineId &&
          metadataEngineVersion == other.metadataEngineVersion &&
          captureTime == other.captureTime;
}

class CaptureTimeEvidence {
  final String localTime;
  final int? offsetMinutes;
  final CaptureTimeSource source;
  final String rawValue;

  const CaptureTimeEvidence({
    required this.localTime,
    this.offsetMinutes,
    required this.source,
    required this.rawValue,
  });

  @override
  int get hashCode =>
      localTime.hashCode ^
      offsetMinutes.hashCode ^
      source.hashCode ^
      rawValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureTimeEvidence &&
          runtimeType == other.runtimeType &&
          localTime == other.localTime &&
          offsetMinutes == other.offsetMinutes &&
          source == other.source &&
          rawValue == other.rawValue;
}

enum CaptureTimeSource { original, digitized, image }

class CatalogCursor {
  final BigInt revision;
  final String queryId;
  final bool primaryMissing;
  final String primaryText;
  final PlatformInt64 primaryNumber;
  final String rootId;
  final String locationId;

  const CatalogCursor({
    required this.revision,
    required this.queryId,
    required this.primaryMissing,
    required this.primaryText,
    required this.primaryNumber,
    required this.rootId,
    required this.locationId,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      queryId.hashCode ^
      primaryMissing.hashCode ^
      primaryText.hashCode ^
      primaryNumber.hashCode ^
      rootId.hashCode ^
      locationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogCursor &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          queryId == other.queryId &&
          primaryMissing == other.primaryMissing &&
          primaryText == other.primaryText &&
          primaryNumber == other.primaryNumber &&
          rootId == other.rootId &&
          locationId == other.locationId;
}

class CatalogSnapshot {
  final String catalogPath;
  final BigInt revision;
  final String queryId;
  final List<LibraryRootView> roots;
  final List<AssetLocationView> assets;
  final CatalogCursor? previousCursor;
  final CatalogCursor? nextCursor;

  const CatalogSnapshot({
    required this.catalogPath,
    required this.revision,
    required this.queryId,
    required this.roots,
    required this.assets,
    this.previousCursor,
    this.nextCursor,
  });

  @override
  int get hashCode =>
      catalogPath.hashCode ^
      revision.hashCode ^
      queryId.hashCode ^
      roots.hashCode ^
      assets.hashCode ^
      previousCursor.hashCode ^
      nextCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogSnapshot &&
          runtimeType == other.runtimeType &&
          catalogPath == other.catalogPath &&
          revision == other.revision &&
          queryId == other.queryId &&
          roots == other.roots &&
          assets == other.assets &&
          previousCursor == other.previousCursor &&
          nextCursor == other.nextCursor;
}

class FileIdentityEvidence {
  final String scheme;
  final String value;

  const FileIdentityEvidence({required this.scheme, required this.value});

  @override
  int get hashCode => scheme.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileIdentityEvidence &&
          runtimeType == other.runtimeType &&
          scheme == other.scheme &&
          value == other.value;
}

class GalleryLayoutDateGroup {
  final String? dateKey;

  const GalleryLayoutDateGroup({this.dateKey});

  @override
  int get hashCode => dateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryLayoutDateGroup &&
          runtimeType == other.runtimeType &&
          dateKey == other.dateKey;
}

class GalleryLayoutManifestChunk {
  final BigInt revision;
  final String queryId;
  final BigInt totalItems;
  final BigInt startOrdinal;
  final List<String> locationIds;
  final Uint16List aspectRatioMilli;
  final Uint16List dateGroupIndices;
  final List<GalleryLayoutDateGroup> dateGroups;
  final Uint8List flags;
  final GalleryLayoutManifestCursor? nextCursor;

  const GalleryLayoutManifestChunk({
    required this.revision,
    required this.queryId,
    required this.totalItems,
    required this.startOrdinal,
    required this.locationIds,
    required this.aspectRatioMilli,
    required this.dateGroupIndices,
    required this.dateGroups,
    required this.flags,
    this.nextCursor,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      queryId.hashCode ^
      totalItems.hashCode ^
      startOrdinal.hashCode ^
      locationIds.hashCode ^
      aspectRatioMilli.hashCode ^
      dateGroupIndices.hashCode ^
      dateGroups.hashCode ^
      flags.hashCode ^
      nextCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryLayoutManifestChunk &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          queryId == other.queryId &&
          totalItems == other.totalItems &&
          startOrdinal == other.startOrdinal &&
          locationIds == other.locationIds &&
          aspectRatioMilli == other.aspectRatioMilli &&
          dateGroupIndices == other.dateGroupIndices &&
          dateGroups == other.dateGroups &&
          flags == other.flags &&
          nextCursor == other.nextCursor;
}

class GalleryLayoutManifestCursor {
  final BigInt revision;
  final String queryId;
  final BigInt totalItems;
  final BigInt nextOrdinal;
  final CatalogCursor after;

  const GalleryLayoutManifestCursor({
    required this.revision,
    required this.queryId,
    required this.totalItems,
    required this.nextOrdinal,
    required this.after,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      queryId.hashCode ^
      totalItems.hashCode ^
      nextOrdinal.hashCode ^
      after.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryLayoutManifestCursor &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          queryId == other.queryId &&
          totalItems == other.totalItems &&
          nextOrdinal == other.nextOrdinal &&
          after == other.after;
}

class GalleryQuery {
  final String? rootId;
  final String? folderRelativePath;
  final bool includeDescendants;
  final String searchText;
  final GallerySortKey sortKey;
  final GallerySortDirection sortDirection;

  const GalleryQuery({
    this.rootId,
    this.folderRelativePath,
    required this.includeDescendants,
    required this.searchText,
    required this.sortKey,
    required this.sortDirection,
  });

  @override
  int get hashCode =>
      rootId.hashCode ^
      folderRelativePath.hashCode ^
      includeDescendants.hashCode ^
      searchText.hashCode ^
      sortKey.hashCode ^
      sortDirection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryQuery &&
          runtimeType == other.runtimeType &&
          rootId == other.rootId &&
          folderRelativePath == other.folderRelativePath &&
          includeDescendants == other.includeDescendants &&
          searchText == other.searchText &&
          sortKey == other.sortKey &&
          sortDirection == other.sortDirection;
}

enum GallerySortDirection { ascending, descending }

enum GallerySortKey { captureTime, createdTime, modifiedTime, fileName }

class GalleryTimeAnchor {
  final BigInt revision;
  final String queryId;
  final String? monthKey;
  final BigInt itemOffset;

  const GalleryTimeAnchor({
    required this.revision,
    required this.queryId,
    this.monthKey,
    required this.itemOffset,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      queryId.hashCode ^
      monthKey.hashCode ^
      itemOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryTimeAnchor &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          queryId == other.queryId &&
          monthKey == other.monthKey &&
          itemOffset == other.itemOffset;
}

class GalleryTimeBucket {
  final String? monthKey;
  final BigInt itemCount;
  final BigInt aspectRatioMilliSum;

  const GalleryTimeBucket({
    this.monthKey,
    required this.itemCount,
    required this.aspectRatioMilliSum,
  });

  @override
  int get hashCode =>
      monthKey.hashCode ^ itemCount.hashCode ^ aspectRatioMilliSum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryTimeBucket &&
          runtimeType == other.runtimeType &&
          monthKey == other.monthKey &&
          itemCount == other.itemCount &&
          aspectRatioMilliSum == other.aspectRatioMilliSum;
}

class GalleryTimeline {
  final BigInt revision;
  final String queryId;
  final BigInt totalItems;
  final List<GalleryTimeBucket> buckets;

  const GalleryTimeline({
    required this.revision,
    required this.queryId,
    required this.totalItems,
    required this.buckets,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      queryId.hashCode ^
      totalItems.hashCode ^
      buckets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryTimeline &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          queryId == other.queryId &&
          totalItems == other.totalItems &&
          buckets == other.buckets;
}

class LibraryFolderCursor {
  final BigInt revision;
  final String rootId;
  final String parentRelativePath;
  final String relativePath;

  const LibraryFolderCursor({
    required this.revision,
    required this.rootId,
    required this.parentRelativePath,
    required this.relativePath,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      rootId.hashCode ^
      parentRelativePath.hashCode ^
      relativePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryFolderCursor &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          rootId == other.rootId &&
          parentRelativePath == other.parentRelativePath &&
          relativePath == other.relativePath;
}

class LibraryFolderPage {
  final BigInt revision;
  final String rootId;
  final String parentRelativePath;
  final List<LibraryFolderView> folders;
  final LibraryFolderCursor? nextCursor;

  const LibraryFolderPage({
    required this.revision,
    required this.rootId,
    required this.parentRelativePath,
    required this.folders,
    this.nextCursor,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      rootId.hashCode ^
      parentRelativePath.hashCode ^
      folders.hashCode ^
      nextCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryFolderPage &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          rootId == other.rootId &&
          parentRelativePath == other.parentRelativePath &&
          folders == other.folders &&
          nextCursor == other.nextCursor;
}

class LibraryFolderView {
  final String rootId;
  final String relativePath;
  final String name;
  final BigInt directAssetCount;
  final BigInt descendantAssetCount;

  const LibraryFolderView({
    required this.rootId,
    required this.relativePath,
    required this.name,
    required this.directAssetCount,
    required this.descendantAssetCount,
  });

  @override
  int get hashCode =>
      rootId.hashCode ^
      relativePath.hashCode ^
      name.hashCode ^
      directAssetCount.hashCode ^
      descendantAssetCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryFolderView &&
          runtimeType == other.runtimeType &&
          rootId == other.rootId &&
          relativePath == other.relativePath &&
          name == other.name &&
          directAssetCount == other.directAssetCount &&
          descendantAssetCount == other.descendantAssetCount;
}

enum LibraryRootAvailability {
  unknown,
  available,
  missing,
  inaccessible,
  offline,
}

class LibraryRootView {
  final String rootId;
  final String path;
  final String displayPath;
  final String? activeScanId;
  final PlatformInt64 createdUnixMs;
  final BigInt assetCount;
  final BigInt issueCount;
  final LibraryRootAvailability availability;
  final String? availabilityMessage;

  const LibraryRootView({
    required this.rootId,
    required this.path,
    required this.displayPath,
    this.activeScanId,
    required this.createdUnixMs,
    required this.assetCount,
    required this.issueCount,
    required this.availability,
    this.availabilityMessage,
  });

  @override
  int get hashCode =>
      rootId.hashCode ^
      path.hashCode ^
      displayPath.hashCode ^
      activeScanId.hashCode ^
      createdUnixMs.hashCode ^
      assetCount.hashCode ^
      issueCount.hashCode ^
      availability.hashCode ^
      availabilityMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryRootView &&
          runtimeType == other.runtimeType &&
          rootId == other.rootId &&
          path == other.path &&
          displayPath == other.displayPath &&
          activeScanId == other.activeScanId &&
          createdUnixMs == other.createdUnixMs &&
          assetCount == other.assetCount &&
          issueCount == other.issueCount &&
          availability == other.availability &&
          availabilityMessage == other.availabilityMessage;
}

class PreviewRequest {
  final String locationId;
  final int previewEdge;
  final bool retryFailed;

  const PreviewRequest({
    required this.locationId,
    required this.previewEdge,
    required this.retryFailed,
  });

  @override
  int get hashCode =>
      locationId.hashCode ^ previewEdge.hashCode ^ retryFailed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewRequest &&
          runtimeType == other.runtimeType &&
          locationId == other.locationId &&
          previewEdge == other.previewEdge &&
          retryFailed == other.retryFailed;
}

enum PreviewStatus { pending, ready, failed }

class RecoverableScan {
  final String scanId;
  final String rootPath;
  final String displayRootPath;
  final int? maxItems;
  final int? maxEntries;
  final int previewEdge;
  final BigInt visitedEntries;
  final BigInt acceptedItems;
  final BigInt issueCount;

  const RecoverableScan({
    required this.scanId,
    required this.rootPath,
    required this.displayRootPath,
    this.maxItems,
    this.maxEntries,
    required this.previewEdge,
    required this.visitedEntries,
    required this.acceptedItems,
    required this.issueCount,
  });

  @override
  int get hashCode =>
      scanId.hashCode ^
      rootPath.hashCode ^
      displayRootPath.hashCode ^
      maxItems.hashCode ^
      maxEntries.hashCode ^
      previewEdge.hashCode ^
      visitedEntries.hashCode ^
      acceptedItems.hashCode ^
      issueCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoverableScan &&
          runtimeType == other.runtimeType &&
          scanId == other.scanId &&
          rootPath == other.rootPath &&
          displayRootPath == other.displayRootPath &&
          maxItems == other.maxItems &&
          maxEntries == other.maxEntries &&
          previewEdge == other.previewEdge &&
          visitedEntries == other.visitedEntries &&
          acceptedItems == other.acceptedItems &&
          issueCount == other.issueCount;
}

class ScanError implements FrbException {
  final String code;
  final String message;

  const ScanError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

@freezed
sealed class ScanEvent with _$ScanEvent {
  const ScanEvent._();

  const factory ScanEvent.started({
    required String scanId,
    required String rootPath,
    int? itemLimit,
    int? entryLimit,
  }) = ScanEvent_Started;
  const factory ScanEvent.progress({
    required String scanId,
    required BigInt visitedEntries,
    required BigInt acceptedItems,
    required BigInt issueCount,
  }) = ScanEvent_Progress;
  const factory ScanEvent.finalizing({
    required String scanId,
    required BigInt validatedItems,
    required BigInt totalItems,
    required BigInt visitedEntries,
    required BigInt acceptedItems,
    required BigInt issueCount,
  }) = ScanEvent_Finalizing;
  const factory ScanEvent.assetDiscovered({
    required String scanId,
    required AssetLocationView asset,
  }) = ScanEvent_AssetDiscovered;
  const factory ScanEvent.issue({
    required String scanId,
    required ScanIssue issue,
  }) = ScanEvent_Issue;
  const factory ScanEvent.completed({
    required String scanId,
    required String rootId,
    required BigInt assetCount,
    required BigInt issueCount,
    required String catalogPath,
    required bool wasLimited,
  }) = ScanEvent_Completed;
  const factory ScanEvent.cancelled({
    required String scanId,
    required BigInt acceptedItems,
    required BigInt issueCount,
  }) = ScanEvent_Cancelled;
  const factory ScanEvent.paused({
    required String scanId,
    required BigInt visitedEntries,
    required BigInt acceptedItems,
    required BigInt issueCount,
  }) = ScanEvent_Paused;
  const factory ScanEvent.stale({
    required String scanId,
    required BigInt acceptedItems,
    required BigInt issueCount,
  }) = ScanEvent_Stale;
  const factory ScanEvent.failed({
    required String scanId,
    required String code,
    required String message,
  }) = ScanEvent_Failed;
}

class ScanIssue {
  final String? path;
  final String code;
  final String message;

  const ScanIssue({this.path, required this.code, required this.message});

  @override
  int get hashCode => path.hashCode ^ code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanIssue &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          code == other.code &&
          message == other.message;
}

class ScanRequest {
  final String scanId;
  final String rootPath;
  final int? maxItems;
  final int? maxEntries;
  final int previewEdge;

  const ScanRequest({
    required this.scanId,
    required this.rootPath,
    this.maxItems,
    this.maxEntries,
    required this.previewEdge,
  });

  @override
  int get hashCode =>
      scanId.hashCode ^
      rootPath.hashCode ^
      maxItems.hashCode ^
      maxEntries.hashCode ^
      previewEdge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanRequest &&
          runtimeType == other.runtimeType &&
          scanId == other.scanId &&
          rootPath == other.rootPath &&
          maxItems == other.maxItems &&
          maxEntries == other.maxEntries &&
          previewEdge == other.previewEdge;
}

class StorageSettingsUpdate {
  final String? catalogDirectory;
  final String? previewCacheDirectory;
  final BigInt previewBudgetBytes;

  const StorageSettingsUpdate({
    this.catalogDirectory,
    this.previewCacheDirectory,
    required this.previewBudgetBytes,
  });

  @override
  int get hashCode =>
      catalogDirectory.hashCode ^
      previewCacheDirectory.hashCode ^
      previewBudgetBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageSettingsUpdate &&
          runtimeType == other.runtimeType &&
          catalogDirectory == other.catalogDirectory &&
          previewCacheDirectory == other.previewCacheDirectory &&
          previewBudgetBytes == other.previewBudgetBytes;
}

class StorageStatus {
  final String settingsPath;
  final String activeCatalogPath;
  final String activePreviewRoot;
  final String configuredCatalogPath;
  final String configuredPreviewRoot;
  final String configuredCatalogDisplayPath;
  final String configuredPreviewDisplayPath;
  final BigInt previewBudgetBytes;
  final BigInt previewUsedBytes;
  final BigInt catalogUsedBytes;
  final bool requiresRestart;

  const StorageStatus({
    required this.settingsPath,
    required this.activeCatalogPath,
    required this.activePreviewRoot,
    required this.configuredCatalogPath,
    required this.configuredPreviewRoot,
    required this.configuredCatalogDisplayPath,
    required this.configuredPreviewDisplayPath,
    required this.previewBudgetBytes,
    required this.previewUsedBytes,
    required this.catalogUsedBytes,
    required this.requiresRestart,
  });

  @override
  int get hashCode =>
      settingsPath.hashCode ^
      activeCatalogPath.hashCode ^
      activePreviewRoot.hashCode ^
      configuredCatalogPath.hashCode ^
      configuredPreviewRoot.hashCode ^
      configuredCatalogDisplayPath.hashCode ^
      configuredPreviewDisplayPath.hashCode ^
      previewBudgetBytes.hashCode ^
      previewUsedBytes.hashCode ^
      catalogUsedBytes.hashCode ^
      requiresRestart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageStatus &&
          runtimeType == other.runtimeType &&
          settingsPath == other.settingsPath &&
          activeCatalogPath == other.activeCatalogPath &&
          activePreviewRoot == other.activePreviewRoot &&
          configuredCatalogPath == other.configuredCatalogPath &&
          configuredPreviewRoot == other.configuredPreviewRoot &&
          configuredCatalogDisplayPath == other.configuredCatalogDisplayPath &&
          configuredPreviewDisplayPath == other.configuredPreviewDisplayPath &&
          previewBudgetBytes == other.previewBudgetBytes &&
          previewUsedBytes == other.previewUsedBytes &&
          catalogUsedBytes == other.catalogUsedBytes &&
          requiresRestart == other.requiresRestart;
}
