// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/catalog.dart';
import 'api/preview.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'domain.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ScanEvent> dco_decode_StreamSink_scan_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AssetLocationView dco_decode_asset_location_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AssetLocationView dco_decode_box_asset_location_view(dynamic raw);

  @protected
  CaptureTimeEvidence dco_decode_box_autoadd_capture_time_evidence(dynamic raw);

  @protected
  CatalogCursor dco_decode_box_autoadd_catalog_cursor(dynamic raw);

  @protected
  FileIdentityEvidence dco_decode_box_autoadd_file_identity_evidence(
    dynamic raw,
  );

  @protected
  GalleryQuery dco_decode_box_autoadd_gallery_query(dynamic raw);

  @protected
  GalleryTimeAnchor dco_decode_box_autoadd_gallery_time_anchor(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_16(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LibraryFolderCursor dco_decode_box_autoadd_library_folder_cursor(dynamic raw);

  @protected
  PreviewRequest dco_decode_box_autoadd_preview_request(dynamic raw);

  @protected
  RecoverableScan dco_decode_box_autoadd_recoverable_scan(dynamic raw);

  @protected
  ScanIssue dco_decode_box_autoadd_scan_issue(dynamic raw);

  @protected
  ScanRequest dco_decode_box_autoadd_scan_request(dynamic raw);

  @protected
  StorageSettingsUpdate dco_decode_box_autoadd_storage_settings_update(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CaptureTimeEvidence dco_decode_capture_time_evidence(dynamic raw);

  @protected
  CaptureTimeSource dco_decode_capture_time_source(dynamic raw);

  @protected
  CatalogCursor dco_decode_catalog_cursor(dynamic raw);

  @protected
  CatalogSnapshot dco_decode_catalog_snapshot(dynamic raw);

  @protected
  FileIdentityEvidence dco_decode_file_identity_evidence(dynamic raw);

  @protected
  GalleryQuery dco_decode_gallery_query(dynamic raw);

  @protected
  GallerySortDirection dco_decode_gallery_sort_direction(dynamic raw);

  @protected
  GallerySortKey dco_decode_gallery_sort_key(dynamic raw);

  @protected
  GalleryTimeAnchor dco_decode_gallery_time_anchor(dynamic raw);

  @protected
  GalleryTimeBucket dco_decode_gallery_time_bucket(dynamic raw);

  @protected
  GalleryTimeline dco_decode_gallery_timeline(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LibraryFolderCursor dco_decode_library_folder_cursor(dynamic raw);

  @protected
  LibraryFolderPage dco_decode_library_folder_page(dynamic raw);

  @protected
  LibraryFolderView dco_decode_library_folder_view(dynamic raw);

  @protected
  LibraryRootAvailability dco_decode_library_root_availability(dynamic raw);

  @protected
  LibraryRootView dco_decode_library_root_view(dynamic raw);

  @protected
  List<AssetLocationView> dco_decode_list_asset_location_view(dynamic raw);

  @protected
  List<GalleryTimeBucket> dco_decode_list_gallery_time_bucket(dynamic raw);

  @protected
  List<LibraryFolderView> dco_decode_list_library_folder_view(dynamic raw);

  @protected
  List<LibraryRootView> dco_decode_list_library_root_view(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CaptureTimeEvidence? dco_decode_opt_box_autoadd_capture_time_evidence(
    dynamic raw,
  );

  @protected
  CatalogCursor? dco_decode_opt_box_autoadd_catalog_cursor(dynamic raw);

  @protected
  FileIdentityEvidence? dco_decode_opt_box_autoadd_file_identity_evidence(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_i_16(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LibraryFolderCursor? dco_decode_opt_box_autoadd_library_folder_cursor(
    dynamic raw,
  );

  @protected
  RecoverableScan? dco_decode_opt_box_autoadd_recoverable_scan(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PreviewRequest dco_decode_preview_request(dynamic raw);

  @protected
  PreviewStatus dco_decode_preview_status(dynamic raw);

  @protected
  RecoverableScan dco_decode_recoverable_scan(dynamic raw);

  @protected
  ScanError dco_decode_scan_error(dynamic raw);

  @protected
  ScanEvent dco_decode_scan_event(dynamic raw);

  @protected
  ScanIssue dco_decode_scan_issue(dynamic raw);

  @protected
  ScanRequest dco_decode_scan_request(dynamic raw);

  @protected
  StorageSettingsUpdate dco_decode_storage_settings_update(dynamic raw);

  @protected
  StorageStatus dco_decode_storage_status(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ScanEvent> sse_decode_StreamSink_scan_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AssetLocationView sse_decode_asset_location_view(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AssetLocationView sse_decode_box_asset_location_view(
    SseDeserializer deserializer,
  );

  @protected
  CaptureTimeEvidence sse_decode_box_autoadd_capture_time_evidence(
    SseDeserializer deserializer,
  );

  @protected
  CatalogCursor sse_decode_box_autoadd_catalog_cursor(
    SseDeserializer deserializer,
  );

  @protected
  FileIdentityEvidence sse_decode_box_autoadd_file_identity_evidence(
    SseDeserializer deserializer,
  );

  @protected
  GalleryQuery sse_decode_box_autoadd_gallery_query(
    SseDeserializer deserializer,
  );

  @protected
  GalleryTimeAnchor sse_decode_box_autoadd_gallery_time_anchor(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_16(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LibraryFolderCursor sse_decode_box_autoadd_library_folder_cursor(
    SseDeserializer deserializer,
  );

  @protected
  PreviewRequest sse_decode_box_autoadd_preview_request(
    SseDeserializer deserializer,
  );

  @protected
  RecoverableScan sse_decode_box_autoadd_recoverable_scan(
    SseDeserializer deserializer,
  );

  @protected
  ScanIssue sse_decode_box_autoadd_scan_issue(SseDeserializer deserializer);

  @protected
  ScanRequest sse_decode_box_autoadd_scan_request(SseDeserializer deserializer);

  @protected
  StorageSettingsUpdate sse_decode_box_autoadd_storage_settings_update(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CaptureTimeEvidence sse_decode_capture_time_evidence(
    SseDeserializer deserializer,
  );

  @protected
  CaptureTimeSource sse_decode_capture_time_source(
    SseDeserializer deserializer,
  );

  @protected
  CatalogCursor sse_decode_catalog_cursor(SseDeserializer deserializer);

  @protected
  CatalogSnapshot sse_decode_catalog_snapshot(SseDeserializer deserializer);

  @protected
  FileIdentityEvidence sse_decode_file_identity_evidence(
    SseDeserializer deserializer,
  );

  @protected
  GalleryQuery sse_decode_gallery_query(SseDeserializer deserializer);

  @protected
  GallerySortDirection sse_decode_gallery_sort_direction(
    SseDeserializer deserializer,
  );

  @protected
  GallerySortKey sse_decode_gallery_sort_key(SseDeserializer deserializer);

  @protected
  GalleryTimeAnchor sse_decode_gallery_time_anchor(
    SseDeserializer deserializer,
  );

  @protected
  GalleryTimeBucket sse_decode_gallery_time_bucket(
    SseDeserializer deserializer,
  );

  @protected
  GalleryTimeline sse_decode_gallery_timeline(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LibraryFolderCursor sse_decode_library_folder_cursor(
    SseDeserializer deserializer,
  );

  @protected
  LibraryFolderPage sse_decode_library_folder_page(
    SseDeserializer deserializer,
  );

  @protected
  LibraryFolderView sse_decode_library_folder_view(
    SseDeserializer deserializer,
  );

  @protected
  LibraryRootAvailability sse_decode_library_root_availability(
    SseDeserializer deserializer,
  );

  @protected
  LibraryRootView sse_decode_library_root_view(SseDeserializer deserializer);

  @protected
  List<AssetLocationView> sse_decode_list_asset_location_view(
    SseDeserializer deserializer,
  );

  @protected
  List<GalleryTimeBucket> sse_decode_list_gallery_time_bucket(
    SseDeserializer deserializer,
  );

  @protected
  List<LibraryFolderView> sse_decode_list_library_folder_view(
    SseDeserializer deserializer,
  );

  @protected
  List<LibraryRootView> sse_decode_list_library_root_view(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CaptureTimeEvidence? sse_decode_opt_box_autoadd_capture_time_evidence(
    SseDeserializer deserializer,
  );

  @protected
  CatalogCursor? sse_decode_opt_box_autoadd_catalog_cursor(
    SseDeserializer deserializer,
  );

  @protected
  FileIdentityEvidence? sse_decode_opt_box_autoadd_file_identity_evidence(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_16(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LibraryFolderCursor? sse_decode_opt_box_autoadd_library_folder_cursor(
    SseDeserializer deserializer,
  );

  @protected
  RecoverableScan? sse_decode_opt_box_autoadd_recoverable_scan(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PreviewRequest sse_decode_preview_request(SseDeserializer deserializer);

  @protected
  PreviewStatus sse_decode_preview_status(SseDeserializer deserializer);

  @protected
  RecoverableScan sse_decode_recoverable_scan(SseDeserializer deserializer);

  @protected
  ScanError sse_decode_scan_error(SseDeserializer deserializer);

  @protected
  ScanEvent sse_decode_scan_event(SseDeserializer deserializer);

  @protected
  ScanIssue sse_decode_scan_issue(SseDeserializer deserializer);

  @protected
  ScanRequest sse_decode_scan_request(SseDeserializer deserializer);

  @protected
  StorageSettingsUpdate sse_decode_storage_settings_update(
    SseDeserializer deserializer,
  );

  @protected
  StorageStatus sse_decode_storage_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_scan_event_Sse(
    RustStreamSink<ScanEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_asset_location_view(
    AssetLocationView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_asset_location_view(
    AssetLocationView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_capture_time_evidence(
    CaptureTimeEvidence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_catalog_cursor(
    CatalogCursor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_file_identity_evidence(
    FileIdentityEvidence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gallery_query(
    GalleryQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gallery_time_anchor(
    GalleryTimeAnchor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_library_folder_cursor(
    LibraryFolderCursor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_preview_request(
    PreviewRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_recoverable_scan(
    RecoverableScan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scan_issue(
    ScanIssue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scan_request(
    ScanRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_storage_settings_update(
    StorageSettingsUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_capture_time_evidence(
    CaptureTimeEvidence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_capture_time_source(
    CaptureTimeSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_catalog_cursor(CatalogCursor self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_snapshot(
    CatalogSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_identity_evidence(
    FileIdentityEvidence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gallery_query(GalleryQuery self, SseSerializer serializer);

  @protected
  void sse_encode_gallery_sort_direction(
    GallerySortDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gallery_sort_key(
    GallerySortKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gallery_time_anchor(
    GalleryTimeAnchor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gallery_time_bucket(
    GalleryTimeBucket self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gallery_timeline(
    GalleryTimeline self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library_folder_cursor(
    LibraryFolderCursor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_folder_page(
    LibraryFolderPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_folder_view(
    LibraryFolderView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_root_availability(
    LibraryRootAvailability self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_root_view(
    LibraryRootView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_asset_location_view(
    List<AssetLocationView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gallery_time_bucket(
    List<GalleryTimeBucket> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_library_folder_view(
    List<LibraryFolderView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_library_root_view(
    List<LibraryRootView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_capture_time_evidence(
    CaptureTimeEvidence? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_catalog_cursor(
    CatalogCursor? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_file_identity_evidence(
    FileIdentityEvidence? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_library_folder_cursor(
    LibraryFolderCursor? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_recoverable_scan(
    RecoverableScan? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_preview_request(
    PreviewRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_preview_status(PreviewStatus self, SseSerializer serializer);

  @protected
  void sse_encode_recoverable_scan(
    RecoverableScan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_error(ScanError self, SseSerializer serializer);

  @protected
  void sse_encode_scan_event(ScanEvent self, SseSerializer serializer);

  @protected
  void sse_encode_scan_issue(ScanIssue self, SseSerializer serializer);

  @protected
  void sse_encode_scan_request(ScanRequest self, SseSerializer serializer);

  @protected
  void sse_encode_storage_settings_update(
    StorageSettingsUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_storage_status(StorageStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
