// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ViewerSourceRequest {
  final String locationId;
  final String expectedRootId;
  final String expectedScanId;
  final SourceRevisionEvidence? expectedSourceRevision;
  final BigInt expectedSourceGeneration;

  const ViewerSourceRequest({
    required this.locationId,
    required this.expectedRootId,
    required this.expectedScanId,
    this.expectedSourceRevision,
    required this.expectedSourceGeneration,
  });

  @override
  int get hashCode =>
      locationId.hashCode ^
      expectedRootId.hashCode ^
      expectedScanId.hashCode ^
      expectedSourceRevision.hashCode ^
      expectedSourceGeneration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewerSourceRequest &&
          runtimeType == other.runtimeType &&
          locationId == other.locationId &&
          expectedRootId == other.expectedRootId &&
          expectedScanId == other.expectedScanId &&
          expectedSourceRevision == other.expectedSourceRevision &&
          expectedSourceGeneration == other.expectedSourceGeneration;
}
