// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class GalleryQueryAnchor {
  final String requestedLocationId;
  final String? assetId;
  final BigInt fallbackOrdinal;

  const GalleryQueryAnchor({
    required this.requestedLocationId,
    this.assetId,
    required this.fallbackOrdinal,
  });

  @override
  int get hashCode =>
      requestedLocationId.hashCode ^
      assetId.hashCode ^
      fallbackOrdinal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryQueryAnchor &&
          runtimeType == other.runtimeType &&
          requestedLocationId == other.requestedLocationId &&
          assetId == other.assetId &&
          fallbackOrdinal == other.fallbackOrdinal;
}

class GalleryQuerySnapshot {
  final CatalogSnapshot snapshot;
  final GalleryTimeline timeline;

  const GalleryQuerySnapshot({required this.snapshot, required this.timeline});

  @override
  int get hashCode => snapshot.hashCode ^ timeline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryQuerySnapshot &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          timeline == other.timeline;
}
