// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class GalleryTimeIntent {
  final String? monthKey;
  final BigInt itemOffset;

  const GalleryTimeIntent({this.monthKey, required this.itemOffset});

  @override
  int get hashCode => monthKey.hashCode ^ itemOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryTimeIntent &&
          runtimeType == other.runtimeType &&
          monthKey == other.monthKey &&
          itemOffset == other.itemOffset;
}

class GalleryTimeSnapshot {
  final CatalogSnapshot snapshot;
  final GalleryTimeline timeline;
  final GalleryTimeAnchor? anchor;
  final BigInt windowStartOrdinal;

  const GalleryTimeSnapshot({
    required this.snapshot,
    required this.timeline,
    this.anchor,
    required this.windowStartOrdinal,
  });

  @override
  int get hashCode =>
      snapshot.hashCode ^
      timeline.hashCode ^
      anchor.hashCode ^
      windowStartOrdinal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryTimeSnapshot &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          timeline == other.timeline &&
          anchor == other.anchor &&
          windowStartOrdinal == other.windowStartOrdinal;
}
