// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../frb_generated.dart';
import 'library_change.dart';
import 'library_change_queue.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class LibraryRootSynchronizationStatus {
  final String rootId;
  final BigInt rootGeneration;
  final LibraryRootAvailability availability;
  final CatalogFreshnessState freshness;
  final CatalogFreshnessCause freshnessCause;
  final LibrarySynchronizationPhase phase;
  final LibraryChangeSourceHealth sourceHealth;
  final LibraryChangeQueueHealth queueHealth;
  final BigInt pendingChangeCount;
  final BigInt retryWaitCount;
  final BigInt freshnessUnknownCount;
  final bool recoveryBlocked;
  final String? lastIssueCode;

  const LibraryRootSynchronizationStatus({
    required this.rootId,
    required this.rootGeneration,
    required this.availability,
    required this.freshness,
    required this.freshnessCause,
    required this.phase,
    required this.sourceHealth,
    required this.queueHealth,
    required this.pendingChangeCount,
    required this.retryWaitCount,
    required this.freshnessUnknownCount,
    required this.recoveryBlocked,
    this.lastIssueCode,
  });

  @override
  int get hashCode =>
      rootId.hashCode ^
      rootGeneration.hashCode ^
      availability.hashCode ^
      freshness.hashCode ^
      freshnessCause.hashCode ^
      phase.hashCode ^
      sourceHealth.hashCode ^
      queueHealth.hashCode ^
      pendingChangeCount.hashCode ^
      retryWaitCount.hashCode ^
      freshnessUnknownCount.hashCode ^
      recoveryBlocked.hashCode ^
      lastIssueCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryRootSynchronizationStatus &&
          runtimeType == other.runtimeType &&
          rootId == other.rootId &&
          rootGeneration == other.rootGeneration &&
          availability == other.availability &&
          freshness == other.freshness &&
          freshnessCause == other.freshnessCause &&
          phase == other.phase &&
          sourceHealth == other.sourceHealth &&
          queueHealth == other.queueHealth &&
          pendingChangeCount == other.pendingChangeCount &&
          retryWaitCount == other.retryWaitCount &&
          freshnessUnknownCount == other.freshnessUnknownCount &&
          recoveryBlocked == other.recoveryBlocked &&
          lastIssueCode == other.lastIssueCode;
}

enum LibrarySynchronizationPhase {
  watcherStartup,
  inventoryEnumeration,
  inventoryComparison,
  queuePublication,
  retryWait,
  reconciliation,
  fullScan,
  blocked,
  synchronized,
  unavailable,
}

class LibrarySynchronizationSnapshot {
  final bool isRunning;
  final BigInt catalogRevision;
  final int appliedMutationCount;
  final List<LibraryRootSynchronizationStatus> roots;

  const LibrarySynchronizationSnapshot({
    required this.isRunning,
    required this.catalogRevision,
    required this.appliedMutationCount,
    required this.roots,
  });

  @override
  int get hashCode =>
      isRunning.hashCode ^
      catalogRevision.hashCode ^
      appliedMutationCount.hashCode ^
      roots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibrarySynchronizationSnapshot &&
          runtimeType == other.runtimeType &&
          isRunning == other.isRunning &&
          catalogRevision == other.catalogRevision &&
          appliedMutationCount == other.appliedMutationCount &&
          roots == other.roots;
}
