param(
    [switch]$Check,
    [string]$PolicyPath = (Join-Path $PSScriptRoot "library_synchronization_poll_interval_ms.txt"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\lib\features\library\application\library_synchronization_policy.g.dart")
)

$ErrorActionPreference = "Stop"
$dartDurationMaximumMilliseconds = [uint64]9223372036854775

function Read-LibrarySynchronizationPollIntervalMilliseconds {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $bytes = [System.IO.File]::ReadAllBytes($Path)
    if ($bytes.Length -lt 2 -or $bytes[$bytes.Length - 1] -ne 10) {
        throw "Library synchronization policy must be one positive decimal integer followed by LF."
    }

    for ($index = 0; $index -lt $bytes.Length - 1; $index += 1) {
        if ($bytes[$index] -lt 48 -or $bytes[$index] -gt 57) {
            throw "Library synchronization policy contains a non-decimal byte at offset $index."
        }
    }

    if ($bytes[0] -eq 48) {
        throw "Library synchronization policy must be positive and must not contain leading zeroes."
    }

    $digits = [System.Text.Encoding]::ASCII.GetString($bytes, 0, $bytes.Length - 1)
    [uint64]$milliseconds = 0
    $isValid = [uint64]::TryParse(
        $digits,
        [System.Globalization.NumberStyles]::None,
        [System.Globalization.CultureInfo]::InvariantCulture,
        [ref]$milliseconds
    )
    if (-not $isValid -or $milliseconds -eq 0) {
        throw "Library synchronization policy is not a positive unsigned 64-bit integer."
    }
    if ($milliseconds -gt $dartDurationMaximumMilliseconds) {
        throw "Library synchronization policy exceeds the Dart Duration signed 64-bit microsecond range."
    }

    return $milliseconds
}

function Test-EqualBytes {
    param(
        [Parameter(Mandatory = $true)]
        [byte[]]$Actual,
        [Parameter(Mandatory = $true)]
        [byte[]]$Expected
    )

    if ($Actual.Length -ne $Expected.Length) {
        return $false
    }
    for ($index = 0; $index -lt $Expected.Length; $index += 1) {
        if ($Actual[$index] -ne $Expected[$index]) {
            return $false
        }
    }
    return $true
}

$resolvedPolicyPath = [System.IO.Path]::GetFullPath($PolicyPath)
$resolvedOutputPath = [System.IO.Path]::GetFullPath($OutputPath)
$milliseconds = Read-LibrarySynchronizationPollIntervalMilliseconds -Path $resolvedPolicyPath
$expectedSource = @"
// Generated by tool/quality_generate_library_synchronization_policy.ps1.
// Do not edit by hand.

const Duration productionLibrarySynchronizationPollInterval = Duration(
  milliseconds: $milliseconds,
);
"@ -replace "`r`n", "`n"
$expectedSource += "`n"
$utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
$expectedBytes = $utf8WithoutBom.GetBytes($expectedSource)

if ($Check) {
    if (-not [System.IO.File]::Exists($resolvedOutputPath)) {
        throw "Generated library synchronization policy is missing: $resolvedOutputPath"
    }
    $actualBytes = [System.IO.File]::ReadAllBytes($resolvedOutputPath)
    if (-not (Test-EqualBytes -Actual $actualBytes -Expected $expectedBytes)) {
        throw "Generated library synchronization policy is stale or not exact UTF-8/LF: $resolvedOutputPath"
    }
    Write-Output "Library synchronization policy generation is current."
    return
}

$outputDirectory = [System.IO.Path]::GetDirectoryName($resolvedOutputPath)
if (-not [System.IO.Directory]::Exists($outputDirectory)) {
    [System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
}
[System.IO.File]::WriteAllBytes($resolvedOutputPath, $expectedBytes)
Write-Output "Generated library synchronization policy: $resolvedOutputPath"
