// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<ScanEvent> scanLibrary({required ScanRequest request}) =>
    RustLib.instance.api.crateApiCatalogScanLibrary(request: request);

Future<CatalogSnapshot> loadLibraryCatalog({
  required int maxItems,
  required GalleryQuery query,
  CatalogCursor? after,
  CatalogCursor? before,
}) => RustLib.instance.api.crateApiCatalogLoadLibraryCatalog(
  maxItems: maxItems,
  query: query,
  after: after,
  before: before,
);

GalleryTimeline loadLibraryGalleryTimeline({required GalleryQuery query}) =>
    RustLib.instance.api.crateApiCatalogLoadLibraryGalleryTimeline(
      query: query,
    );

Future<GalleryLayoutManifestChunk> loadLibraryGalleryLayoutManifestChunk({
  required int maxItems,
  required GalleryQuery query,
  GalleryLayoutManifestCursor? after,
}) => RustLib.instance.api.crateApiCatalogLoadLibraryGalleryLayoutManifestChunk(
  maxItems: maxItems,
  query: query,
  after: after,
);

LibraryFolderPage loadLibraryFolderPage({
  required String rootId,
  required String parentRelativePath,
  required int maxItems,
  LibraryFolderCursor? after,
}) => RustLib.instance.api.crateApiCatalogLoadLibraryFolderPage(
  rootId: rootId,
  parentRelativePath: parentRelativePath,
  maxItems: maxItems,
  after: after,
);

Future<CatalogSnapshot> loadLibraryCatalogAtTime({
  required int maxItems,
  required GalleryQuery query,
  required GalleryTimeAnchor anchor,
}) => RustLib.instance.api.crateApiCatalogLoadLibraryCatalogAtTime(
  maxItems: maxItems,
  query: query,
  anchor: anchor,
);

bool removeLibraryRoot({required String rootId}) =>
    RustLib.instance.api.crateApiCatalogRemoveLibraryRoot(rootId: rootId);

RecoverableScan? loadRecoverableLibraryScan() =>
    RustLib.instance.api.crateApiCatalogLoadRecoverableLibraryScan();

RecoverableScan? loadPausedLibraryScan() =>
    RustLib.instance.api.crateApiCatalogLoadPausedLibraryScan();

bool cancelLibraryScan({required String scanId}) =>
    RustLib.instance.api.crateApiCatalogCancelLibraryScan(scanId: scanId);

bool pauseLibraryScan({required String scanId}) =>
    RustLib.instance.api.crateApiCatalogPauseLibraryScan(scanId: scanId);
