// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

StorageStatus loadStorageStatus() =>
    RustLib.instance.api.crateApiStorageLoadStorageStatus();

StorageStatus updateStorageSettings({required StorageSettingsUpdate update}) =>
    RustLib.instance.api.crateApiStorageUpdateStorageSettings(update: update);
