// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../domain/library_change.dart';
import '../domain/library_change_queue.dart';
import '../domain/library_synchronization.dart';
import '../domain/persistent_journal.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

BigInt reserveLibrarySynchronizationStartTicket() => RustLib.instance.api
    .crateApiSynchronizationReserveLibrarySynchronizationStartTicket();

BigInt reserveLibrarySynchronizationStopFence() => RustLib.instance.api
    .crateApiSynchronizationReserveLibrarySynchronizationStopFence();

Future<LibrarySynchronizationSnapshot> startLibrarySynchronization({
  required BigInt ownerTicket,
}) => RustLib.instance.api.crateApiSynchronizationStartLibrarySynchronization(
  ownerTicket: ownerTicket,
);

Future<LibrarySynchronizationSnapshot> pollLibrarySynchronization({
  required BigInt ownerTicket,
}) => RustLib.instance.api.crateApiSynchronizationPollLibrarySynchronization(
  ownerTicket: ownerTicket,
);

Future<void> stopLibrarySynchronization({required BigInt cancellationFence}) =>
    RustLib.instance.api.crateApiSynchronizationStopLibrarySynchronization(
      cancellationFence: cancellationFence,
    );
