// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../domain/library_change.dart';
import '../domain/library_change_queue.dart';
import '../domain/library_synchronization.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<LibrarySynchronizationSnapshot> startLibrarySynchronization() =>
    RustLib.instance.api.crateApiSynchronizationStartLibrarySynchronization();

Future<LibrarySynchronizationSnapshot> pollLibrarySynchronization() =>
    RustLib.instance.api.crateApiSynchronizationPollLibrarySynchronization();

Future<void> stopLibrarySynchronization() =>
    RustLib.instance.api.crateApiSynchronizationStopLibrarySynchronization();
