// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../application/viewer_source.dart';
import '../domain.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lease_error`

Future<ViewerSourceReadLease> acquireViewerSource({
  required ViewerSourceRequest request,
}) => RustLib.instance.api.crateApiViewerSourceAcquireViewerSource(
  request: request,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ViewerSourceReadLease>>
abstract class ViewerSourceReadLease implements RustOpaqueInterface {
  Future<void> close();

  Future<String> sourcePath();
}
